import { useContext } from "react"

// Next
import Head from "next/head"

// Components
import { Navbar } from "../components/Navbar"
import { Layout } from "../components/Layout"

// Styles
import styles from "../styles/Home.module.css"
import { ProductCard } from "../components/ProductCard"

// Context
import { ProductContext } from "../context/ProductContext"

export default function Home() {
  const { products } = useContext(ProductContext)

  return (
    <div className={styles.container}>
      <Head>
        <title>Head 01</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="bg-white">
        <Layout>
          <div className="mx-auto max-w-2xl py-10 sm:py-2  lg:max-w-7xl">
            <div className="mt-8 grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
              {products.map((product) => (
                <ProductCard
                  key={product.id}
                  product={product}
                  name={product.name}
                  href={product.href}
                  imageAlt={product.imageAlt}
                  imageSrc={product.imageSrc}
                  id={product.id}
                  color={product.color}
                  price={product.price}
                />
              ))}
            </div>
          </div>
        </Layout>
      </main>
    </div>
  )
}
